trigger:
  batch: true
  branches:
    include:
      - develop
      - uat
      - main
  paths:
    include:
      - ext/log-exporter

pr: none

extends:
  template: /.pipelines/template-backend-service-release.yml
  parameters:
    serviceName: log-exporter
