name: ext
on:
  push:
    tags: [ "*.*.*" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 17
    - uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle') }}
    - uses: actions/cache@v2
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
    - run: ./gradlew -Penv=prod -p ext docker
    - run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - uses: docker/login-action@v1
      with:
        username: neowu
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - uses: docker/build-push-action@v2
      with:
        context: "build/ext/log-processor/docker"
        tags: "neowu/log-processor:${{ env.TAG }}"
        push: true
    - uses: docker/build-push-action@v2
      with:
        context: "build/ext/log-collector/docker"
        tags: "neowu/log-collector:${{ env.TAG }}"
        push: true
    - uses: docker/build-push-action@v2
      with:
        context: "build/ext/monitor/docker"
        tags: "neowu/monitor:${{ env.TAG }}"
        push: true
